production:
  read_only: false                   # default: false
  github_secure: "ziplist_doozers!"  # default: nil
  url_host: "fragglerock.ziplist.com"
  ajax_reload: "building"            # "building" or "always"
  build_dir: "builds"                # default: "builds"
